server:
  port: 8083
spring:
  application:
    name: payment
  datasource:
    url: jdbc:mysql://localhost:3306/payment_gateway
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
app:
  cors:
    allowed-origins: http://localhost:4200,http://127.0.0.1:4200
  mongodb:
    uri: mongodb://localhost:27017
    database: payment_audit
  services:
    auth-service-url: http://localhost:8082
    user-service-url: http://localhost:8081
  kafka:
    topics:
      payment-initiated: payment.initiated
      payment-completed: payment.completed
      payment-failed: payment.failed
      payment-refunded: payment.refunded
springdoc:
  api-docs:
    path: /v3/api-docs/payment
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never
logging:
  level:
    root: INFO
    com.paymentgateway.payment: INFO
    org.hibernate.SQL: DEBUG
